spring.application.name=spring-boot
# Tell Hibernate to automatically create/update the tables based on your @Entity
spring.jpa.hibernate.ddl-auto=update
# See the SQL that Spring is writing for you in the console
spring.jpa.show-sql=true